logging:
  file:
    name: logs/sboard.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080
  servlet:
    context-path: /sboard
spring:
  application:
    name: sboard
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: 1234
    url: jdbc:oracle:thin:@//43.203.167.107:1522/XEPDB1
    username: seolyooo
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
